### PR TITLE
Docs update

### PR DESCRIPTION
**Pull request by MagicLike**
- [x] [Updated docs links index](https://github.com/openandroidinstaller-dev/openandroidinstaller-dev.github.io/commit/e0d3e55dcba7149ce0c0aee061ebf73ed4dfab88)
- [x] [Updated unlock-bootloader section in FAQ](https://github.com/openandroidinstaller-dev/openandroidinstaller-dev.github.io/commit/fc3a38d606b8ea9efbc21a2e6c6f3eaa8c4b48ef)

<details><summary>Preview</summary>

grafik

</details> 

follow up of openandroidinstaller-dev/openandroidinstaller#293

### CODE REVIEW

**Review by tsterbak — APPROVED** [review]
Looks good to me :) I move forward and do the merges.

**Comment by MagicLike** [comment]
> Looks good to me :) I move forward and do the merges.

I'd merge this one into `page-updates` first - if that's fine...

Edit: @tsterbak Because of conflicts I needed to merge into #22... The good thing: I am also almost finished with that one, so that it can be merged with the new OAI release! The only thing that is missing, is a SVG of the OAI JPEG - see https://github.com/openandroidinstaller-dev/openandroidinstaller-dev.github.io/issues/16#issuecomment-1729855472

**Comment by tsterbak** [comment]
> Edit: @tsterbak Because of conflicts I needed to merge into https://github.com/openandroidinstaller-dev/openandroidinstaller-dev.github.io/pull/22... The good thing: I am also almost finished with that one, so that it can be merged with the new OAI release! The only thing that is missing, is a SVG of the OAI JPEG - see https://github.com/openandroidinstaller-dev/openandroidinstaller-dev.github.io/issues/16#issuecomment-1729855472

That will be a bit annoying, and I would have preferred to keep changes necessary for the release separate from other changes. But let's see how it goes.

**Comment by MagicLike** [comment]
> > Edit: @tsterbak Because of conflicts I needed to merge into #22... The good thing: I am also almost finished with that one, so that it can be merged with the new OAI release! The only thing that is missing, is a SVG of the OAI JPEG - see [#16 (comment)](https://github.com/openandroidinstaller-dev/openandroidinstaller-dev.github.io/issues/16#issuecomment-1729855472)
> 
> That will be a bit annoying, and I would have preferred to keep changes necessary for the release separate from other changes. But let's see how it goes.

Also not my favourite choice...

**Pull request merged**
