### PR TITLE
fix kagura device name + xda links

### PR DESCRIPTION
**Pull request by SirRGB**

### CODE REVIEW

**Comment by MagicLike** [comment]
The files in the /public/ directory should not be edited directly. They get generated before release.

**Comment by SirRGB** [comment]
Ic r

**Comment by SirRGB** [comment]
I guess those are auto-generated. Im not familiar with websites...

**Comment by MagicLike** [comment]
You can still edit the files in /templates/ - from there the public files are generated

**Comment by tsterbak** [comment]
Is this ready for release? Looks good to me :)

**Review by tsterbak — APPROVED** [review]

**Review by MagicLike — APPROVED** [review]
LGTM

**Pull request merged**
